Snowflake driver
glg/epiquery2 pull request #61
Opened 2020-09-09 14:33 UTC by mikemartin1090

2020-09-09 15:33 UTC, fearphage requested changes
A few questions and concerns, but it looks good overall.

2020-09-09 15:33 UTC, fearphage commented on package.json
> +    "asn1.js-rfc5280": "3.0.0",
Why are these in the `dependencies`, but I don't see them referenced anywhere in the code?

2020-09-09 15:33 UTC, fearphage commented on package.json
> +    "ocsp": "1.2.0",
Why are these in the `dependencies`, but I don't see them referenced anywhere in the code?

2020-09-09 15:33 UTC, fearphage commented on src/drivers/snowflake.coffee
> +events      = require 'events'
Would it be a huge ask to request that we not add more coffee script to the code base?

2020-09-09 15:33 UTC, fearphage commented on Makefile
> +test: node_modules/
Does this change work from a clean checkout?

2020-09-09 15:33 UTC, fearphage commented on .github/workflows/tests.yml
> +          EPI_C_SNOWFLAKE: '{"driver":"snowflake","config":{"account":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_ACCOUNT_ID }}", "username":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_USERNAME }}", "passwor
MINOR: Can you move the config to the end and everything else to the beginning? This is how the other drivers are setup.

2020-09-09 15:33 UTC, fearphage commented on difftest/templates/test/query_warehouses.snowflake
> +SHOW WAREHOUSES
This file doesn't seem to be referenced. Should it be here?

2020-09-09 21:44 UTC, mikemartin1090 commented on Makefile
> +test: node_modules/
Yes - works from a clean checkout since the templates directory is included in this repo now. This is an artifact of when the templates used to be stored in a separate repo. https://github.com/glg/epiquery2/commit/70239dade17101d8c88d04cfa5b356e04f556ca1

I've also checked it out in my `/tmp` directory and ran `make start`. Output below!

```
➜  /tmp cd epiquery2                                                                                                                                                    [5:39:57]
➜  epiquery2 git:(master) git checkout snowflake-driver                                                                                                                 [5:39:59]
Branch 'snowflake-driver' set up to track remote branch 'snowflake-driver' from 'origin'.
Switched to a new branch 'snowflake-driver'
➜  epiquery2 git:(snowflake-driver) git remote -v                                                                                                                       [5:40:03]
origin	git@github.com:glg/epiquery2.git (fetch)
origin	git@github.com:glg/epiquery2.git (push)
➜  epiquery2 git:(snowflake-driver) make start                                                                                                                          [5:40:10]
exec ./bin/npm-starter
make[1]: Entering directory '/private/tmp/epiquery2'
npm install .

> coffeelint@0.6.1 install /private/tmp/epiquery2/node_modules/coffeelint
> echo 'process.exit(require("fs").existsSync("lib/commandline.js") ? 0 : 1)' | node || npm run compile

** TRUNCATED **

9 Sep 17:40:38 - [88079] [INFO] clearing response transformation cache
9 Sep 17:40:38 - [88079] [WARN] epiquery2 running in development mode, this will cause requests to be slower
9 Sep 17:40:38 - [88079] [DEBUG] server worker process starting with configuration
9 Sep 17:40:38 - [88079] [DEBUG] {"port":"8080","templateDirectory":"/tmp/epiquery2/difftest/templates/","driverDirectory":null,"connections":{"mssql_o":{"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433,"requestTimeout":0}}},"mssql":{"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433,"requestTimeout":0}}},"file":{"driver":"file","config":{},"name":"file"},"mysql":{"name":"mysql","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}},"render":{"driver":"render","config":{},"name":"render"},"sfdc":{"name":"sfdc","driver":"salesforce","config":{"userName":"","password":"","server":"http://sfdc"}},"no_server":{"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}},"timesout":{"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433,"requestTimeout":1}}},"mysql_bulk":{"name":"mysql_bulk","type":"bulk","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}},"snowflake":{"driver":"snowflake","config":{"account":"kma51753.us-east-1","username":"EPIQUERY_SERVICE_ACCOUNT","password":"125$j9K^6oMg"},"name":"snowflake"}},"forks":1,"allowedTemplates":null,"templateChangeFile":"/tmp/epiquery2/difftest/templates/.change","responseTransformDirectory":"/tmp/epiquery2/difftest/templates/response_transforms","nodeEnvironment":"development","urlBasedApiKey":"true","httpRequestTimeoutInSeconds":120,"enableTemplateAcls":"DISABLED","epiScreamerUrl":"https://services.glgresearch.com/epi-screamer/epiquery"}
9 Sep 17:40:38 - [88079] [DEBUG] node version v12.18.3
SockJS v0.3.8 bound to "/sockjs"
9 Sep 17:40:38 - [88079] [WARN] ********************************************************************************
9 Sep 17:40:38 - [88079] [WARN] epiquery is running in development mode, this will result in templates not being cached and thus
9 Sep 17:40:38 - [88079] [WARN] reloaded on every request, this will BE SLOW
9 Sep 17:40:38 - [88079] [WARN] ********************************************************************************
9 Sep 17:40:38 - [88079] [WARN] ********************************************************************************
9 Sep 17:40:38 - [88079] [WARN] epiquery is running in a single fork specified, this results in a single process epiquery which will BE SLOW
9 Sep 17:40:38 - [88079] [WARN] running on port  8080
9 Sep 17:40:38 - [88079] [WARN] ********************************************************************************
^Cmake: *** [Makefile:12: run-server] Interrupt: 2
```

2020-09-14 19:22 UTC, mikemartin1090 commented on difftest/templates/test/query_warehouses.snowflake
> +SHOW WAREHOUSES
I was using it for testing, but no need for an associated test. I'll remove it.

2020-09-14 19:56 UTC, mikemartin1090 commented on .github/workflows/tests.yml
> +          EPI_C_SNOWFLAKE: '{"driver":"snowflake","config":{"account":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_ACCOUNT_ID }}", "username":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_USERNAME }}", "passwor
Good call! Set an example for the rest of us future developers. I've updated .github/workflows/tests.yml and difftest/etc/epi_test_config to make sure it's driver - name - config. https://github.com/glg/epiquery2/pull/61/commits/4ab819a9ca4202d820ddb6aaf5d780f3ead8f633

2020-09-14 20:10 UTC, mikemartin1090 commented on package.json
> +    "ocsp": "1.2.0",
They are a part of snowflake-sdk https://github.com/glg/epiquery2/blob/4ab819a9ca4202d820ddb6aaf5d780f3ead8f633/package-lock.json#L3255

2020-09-14 20:10 UTC, mikemartin1090 commented on package.json
> +    "asn1.js-rfc5280": "3.0.0",
Dependencies of ocsp https://github.com/glg/epiquery2/blob/4ab819a9ca4202d820ddb6aaf5d780f3ead8f633/package-lock.json#L2648-L2650

2020-09-14 20:16 UTC, fearphage commented on package.json
> +    "asn1.js-rfc5280": "3.0.0",
Generally only top-level/immediate/direct dependencies are in the `package.json`. These are secondary and third-level dependencies. 

I'm not sure if you're editing these by hand, but you shouldn't have to. I just tested to see if snowflake-sdk adds this and I didn't see it.

```shell
➜  meh.o4jmAsq cd $(mktemp -d /tmp/meh.XXXXXXX); npm init -y > /dev/null; npm install snowflake-sdk > /dev/null; jq . package.json
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN meh.qNaMIBD@1.0.0 No description
npm WARN meh.qNaMIBD@1.0.0 No repository field.

{
  "name": "meh.qNaMIBD",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "snowflake-sdk": "^1.5.3"
  }
}
```

2020-09-14 20:19 UTC, fearphage commented on package.json
> +    "ocsp": "1.2.0",
See [previous comment](https://github.com/glg/epiquery2/pull/61#discussion_r488194797). If we don't write `require('ocsp')` in our code, it shouldn't be in our dependencies. `snowflake-sdk` could stop using `ocsp` tomorrow and we don't need to care since it's not _our_ dependency.

2020-09-15 20:56 UTC, mikemartin1090 commented on src/drivers/snowflake.coffee
> +events      = require 'events'
It was, but I did it just for you :)

2020-09-15 21:02 UTC, fearphage commented on src/drivers/snowflake.coffee
> +events      = require 'events'
![image](https://user-images.githubusercontent.com/23887/93264497-d462e100-f76c-11ea-950f-318527e9224b.png)

2020-09-15 21:03 UTC, fearphage approved these changes

2020-09-15 21:03 UTC, fearphage commented on src/drivers/snowflake.js
> +const EventEmitter = require('events');
JS > CS :purple_heart:

2020-09-15 21:13 UTC, merged